# Generated by Django 4.2.25 on 2025-10-27 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assessment_questionnaire_riskresult_concernanalysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='free_text',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='student_age',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='student_grade',
        ),
        migrations.RemoveField(
            model_name='concernanalysis',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concernanalysis',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_analyses', to='core.assessment'),
        ),
        migrations.AlterField(
            model_name='concernanalysis',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='concernanalysis',
            name='sentiment',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='riskresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_results', to='core.assessment'),
        ),
        migrations.AlterField(
            model_name='riskresult',
            name='method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='riskresult',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='riskresult',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('educator', 'Educator')], default='parent', max_length=20),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
